In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris, load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import mean_squared_error, r2_score

# Load datasets
iris = load_iris()
X_iris, y_iris = iris.data, iris.target

diabetes = load_diabetes()
X_diab, y_diab = diabetes.data, diabetes.target

# Split datasets
Xi_train, Xi_test, yi_train, yi_test = train_test_split(
    X_iris, y_iris, test_size=0.3, random_state=42)

Xd_train, Xd_test, yd_train, yd_test = train_test_split(
    X_diab, y_diab, test_size=0.3, random_state=42)

In [2]:
id3_iris = DecisionTreeClassifier(criterion="entropy", random_state=42)
id3_iris.fit(Xi_train, yi_train)

yi_pred = id3_iris.predict(Xi_test)

print("ID3 on Iris")
print("Confusion Matrix:\n", confusion_matrix(yi_test, yi_pred))
print("Accuracy:", accuracy_score(yi_test, yi_pred))

ID3 on Iris
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]
Accuracy: 0.9777777777777777


In [3]:
# Convert regression to classification
median = np.median(yd_train)
yd_train_class = (yd_train > median).astype(int)
yd_test_class = (yd_test > median).astype(int)

id3_diab = DecisionTreeClassifier(criterion="entropy", random_state=42)
id3_diab.fit(Xd_train, yd_train_class)

yd_pred_class = id3_diab.predict(Xd_test)

print("ID3 on Diabetes (as Classification)")
print("Confusion Matrix:\n", confusion_matrix(yd_test_class, yd_pred_class))
print("Accuracy:", accuracy_score(yd_test_class, yd_pred_class))

ID3 on Diabetes (as Classification)
Confusion Matrix:
 [[46 26]
 [19 42]]
Accuracy: 0.6616541353383458


In [4]:
cart_iris = DecisionTreeClassifier(criterion="gini", random_state=42)
cart_iris.fit(Xi_train, yi_train)

yi_cart_pred = cart_iris.predict(Xi_test)

print("CART on Iris")
print("Confusion Matrix:\n", confusion_matrix(yi_test, yi_cart_pred))
print("Accuracy:", accuracy_score(yi_test, yi_cart_pred))

CART on Iris
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy: 1.0


In [5]:
cart_diab = DecisionTreeRegressor(random_state=42)
cart_diab.fit(Xd_train, yd_train)

yd_cart_pred = cart_diab.predict(Xd_test)

print("CART on Diabetes (Regression)")
print("MSE:", mean_squared_error(yd_test, yd_cart_pred))
print("RMSE:", np.sqrt(mean_squared_error(yd_test, yd_cart_pred)))
print("R2 Score:", r2_score(yd_test, yd_cart_pred))

CART on Diabetes (Regression)
MSE: 5697.789473684211
RMSE: 75.48370336492647
R2 Score: -0.05547696148647652
